### ISSUE TITLE
Document 'tabulate' requirement for 'report-status'

### ISSUE THREAD

**Issue by maartenflippo** [Dekker1/minizinc-slurm#19]
At the moment, the README documents the `report-status` command. However, just following the setup does not actually provide any output modes. From the code I saw the `tabulate` package needs to be installed, and then it works. Perhaps it would be a good idea to add this to the readme.

**Comment by Dekker1** [comment]
It is noted in the read me:

> Note that these scripts might require some extra dependencies. For this reason, these scripts are not expected to work unless this package is installed as pip install mzn-bench[scripts]. This allows us to install a minimal version on the running cluster and this more complete version locally while processing the data.
