### ISSUE TITLE
Benchmarking with FlatZinc files directly

### ISSUE THREAD

**Issue by ptal** [Dekker1/minizinc-slurm#41]
Hi,

I would like to benchmark with flatzinc files directly (.fzn) instead of .mzn/.dzn files. I could update mzn-bench to allow .fzn files in `mzn-bench collect-instances`. However, I'm a bit stuck on the next error coming from MiniZinc (see below). Any insight and guidance on solving the issue?

Perhaps you don't see the advantage working directly with .fzn, but depending on the version of MiniZinc, different .fzn might be generated from a .mzn/.dzn couple. For replicability, I think it might be better to store the .fzn?
(Although my main motivation here is that I have a bunch of .fzn without corresponding .mzn/.dzn ;-)).

```
python3 test.py
Traceback (most recent call last):
  File "/home/ptalbot/repositories/lattice-land/turbo/benchmarks/test.py", line 8, in <module>
    schedule(
  File "/home/ptalbot/repositories/mzn-bench/src/mzn_bench/mzn_slurm.py", line 148, in schedule
    main(Path(instances), Path(output_dir))
  File "/home/ptalbot/repositories/mzn-bench/src/mzn_bench/mzn_slurm.py", line 302, in main
    asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ptalbot/repositories/mzn-bench/src/mzn_bench/mzn_slurm.py", line 201, in run_instance
    async for result in instance.solutions(
  File "/home/ptalbot/.local/lib/python3.10/site-packages/minizinc/instance.py", line 376, in solutions
    solution, new_status, statistics = self._parse_stream_obj(
  File "/home/ptalbot/.local/lib/python3.10/site-packages/minizinc/instance.py", line 743, in _parse_stream_obj
    tmp = obj["output"]["json"]
KeyError: 'json'
```

**Comment by Dekker1** [comment]
I would normally recommend to directly use different versions of MiniZinc. This is already supported by the toolchain using the `minizinc=` argument to `Configuration`.

If you want to make sure future runs of the experiment run the same version of MiniZinc, then I would recommend adding the MiniZinc source used directly in tests using `git subtree`. See these benchmarks as an example: https://github.com/Dekker1/half-reif-benchmarks/tree/develop

I don't, however, have any objection against being able to run FlatZinc files directly. It should be noted that FlatZinc is solver specific, so using the same FlatZinc file with a different solver, or different version of a solver, will likely result in an error (or suboptimal behaviour). The problem to make this work with `mzn-bench` will likely be in `minizinc-python` or maybe even the MiniZinc compiler. You would likely need to provide the `.ozn` output model in addition to the `.fzn` file, and then there might still be flags used by MiniZinc Python that are incompatible when using FlatZinc models. They would need to be made compatible to ensure the expected output is created, or special running behaviour needs to be implemented in MiniZinc Python.

**Comment by ptal** [comment]
Hmm, I see! Thanks for the insights.
Indeed, pinning to a specific version of MiniZinc might be the easiest solution for reproducibility.
Let's do that, I don't really have the time to modify the Minizinc toolchain for this purpose now.
